'use strict';

module.exports = {
  SDK_MISSING_PARAMETER: 'MISSING_PARAMETER',
  SDK_INVALID_PARAMETER: 'INVALID_PARAMETER',
  SDK_TRANSPORT_ERROR: 'TRANSPORT_ERROR',
  SDK_BAD_SIGNATURE: 'INVALID_RESPONSE_SIGNATURE',
  SDK_UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  SDK_ACCESS_DENIED: 'ACCESS_DENIED',
  SDK_METHOD_NOT_FOUND: 'METHOD_NOT_FOUND',

  PROVIDER_INVALID_PARAMETER: 'INVALID_PARAMETER',
  PROVIDER_BAD_SIGNATURE: 'INVALID_SIGNATURE',
};
